version: "3.7"
services:
  frontend:
    environment:
      - ROCKETCHAT_USERNAME
      - ROCKETCHAT_PASSWORD
    build: frontend
    ports:
      - "127.0.0.1:42773:80"
    networks:
      - backend
  backend:
    build: backend
    networks:
      - backend
      - rocketchat_default

networks:
  backend:
  rocketchat_default:
    external: True
