version: "3.7"
services:
  frontend:
    build: frontend
    ports:
      - "42773:80"
    networks:
      - backend
  backend:
    build: backend
    networks:
      - backend
      - rocketchat_default

networks:
  backend:
  rocketchat_default: